// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UserInfoReq struct {
	UserId int64 `json:"userId"`
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	AccessToken string `json:"accessToken"`
	Expire      int64  `json:"expire"`
}
