// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hello.proto

package hello_client

import (
	"context"

	"Quantum/interface/hello/pb/hello"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = hello.Request
	Response = hello.Response

	Hello interface {
		Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultHello struct {
		cli zrpc.Client
	}
)

func NewHello(cli zrpc.Client) Hello {
	return &defaultHello{
		cli: cli,
	}
}

func (m *defaultHello) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := hello.NewHelloClient(m.cli.Conn())
	return client.Hello(ctx, in, opts...)
}
