// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: demo.proto

package demo_client

import (
	"context"

	"Quantum/interface/demo/pb/demo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserInfoReq   = demo.UserInfoReq
	UserInfoResp  = demo.UserInfoResp
	UserLoginReq  = demo.UserLoginReq
	UserLoginResp = demo.UserLoginResp

	Demo interface {
		// 登录
		Login(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error)
		// 获取用户信息
		UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
	}

	defaultDemo struct {
		cli zrpc.Client
	}
)

func NewDemo(cli zrpc.Client) Demo {
	return &defaultDemo{
		cli: cli,
	}
}

// 登录
func (m *defaultDemo) Login(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error) {
	client := demo.NewDemoClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultDemo) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := demo.NewDemoClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}
