// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: demo.proto

package server

import (
	"context"

	"Quantum/interface/demo/pb/demo"
	"Quantum/service/demo/internal/logic"
	"Quantum/service/demo/internal/svc"
)

type DemoServer struct {
	svcCtx *svc.ServiceContext
	demo.UnimplementedDemoServer
}

func NewDemoServer(svcCtx *svc.ServiceContext) *DemoServer {
	return &DemoServer{
		svcCtx: svcCtx,
	}
}

// 登录
func (s *DemoServer) Login(ctx context.Context, in *demo.UserLoginReq) (*demo.UserLoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 获取用户信息
func (s *DemoServer) UserInfo(ctx context.Context, in *demo.UserInfoReq) (*demo.UserInfoResp, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
