// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserInfoID *int64     `gorm:"column:user_info_id;type:bigint" json:"user_info_id"`
	VideoID    *int64     `gorm:"column:video_id;type:bigint" json:"video_id"`
	Content    *string    `gorm:"column:content;type:longtext" json:"content"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
