// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserLogin = "user_logins"

// UserLogin mapped from table <user_logins>
type UserLogin struct {
	ID         int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserInfoID *int64 `gorm:"column:user_info_id;type:bigint" json:"user_info_id"`
	Username   string `gorm:"column:username;type:varchar(191);primaryKey" json:"username"`
	Password   string `gorm:"column:password;type:varchar(200);not null" json:"password"`
}

// TableName UserLogin's table name
func (*UserLogin) TableName() string {
	return TableNameUserLogin
}
