// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserInfo = "user_infos"

// UserInfo mapped from table <user_infos>
type UserInfo struct {
	ID            int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name          *string `gorm:"column:name;type:longtext" json:"name"`
	FollowCount   *int64  `gorm:"column:follow_count;type:bigint" json:"follow_count"`
	FollowerCount *int64  `gorm:"column:follower_count;type:bigint" json:"follower_count"`
	IsFollow      *bool   `gorm:"column:is_follow;type:tinyint(1)" json:"is_follow"`
}

// TableName UserInfo's table name
func (*UserInfo) TableName() string {
	return TableNameUserInfo
}
