// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "videos"

// Video mapped from table <videos>
type Video struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserInfoID    *int64     `gorm:"column:user_info_id;type:bigint" json:"user_info_id"`
	PlayURL       *string    `gorm:"column:play_url;type:longtext" json:"play_url"`
	CoverURL      *string    `gorm:"column:cover_url;type:longtext" json:"cover_url"`
	FavoriteCount *int64     `gorm:"column:favorite_count;type:bigint" json:"favorite_count"`
	CommentCount  *int64     `gorm:"column:comment_count;type:bigint" json:"comment_count"`
	IsFavorite    *bool      `gorm:"column:is_favorite;type:tinyint(1)" json:"is_favorite"`
	Title         *string    `gorm:"column:title;type:longtext" json:"title"`
	CreatedAt     *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
