// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: user_enum.proto

package user_enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEnum int32

const (
	UserEnum_UserEnumUnknown UserEnum = 0
)

// Enum value maps for UserEnum.
var (
	UserEnum_name = map[int32]string{
		0: "UserEnumUnknown",
	}
	UserEnum_value = map[string]int32{
		"UserEnumUnknown": 0,
	}
)

func (x UserEnum) Enum() *UserEnum {
	p := new(UserEnum)
	*p = x
	return p
}

func (x UserEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_user_enum_proto_enumTypes[0].Descriptor()
}

func (UserEnum) Type() protoreflect.EnumType {
	return &file_user_enum_proto_enumTypes[0]
}

func (x UserEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserEnum.Descriptor instead.
func (UserEnum) EnumDescriptor() ([]byte, []int) {
	return file_user_enum_proto_rawDescGZIP(), []int{0}
}

var File_user_enum_proto protoreflect.FileDescriptor

var file_user_enum_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x2a, 0x1f, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_enum_proto_rawDescOnce sync.Once
	file_user_enum_proto_rawDescData = file_user_enum_proto_rawDesc
)

func file_user_enum_proto_rawDescGZIP() []byte {
	file_user_enum_proto_rawDescOnce.Do(func() {
		file_user_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_enum_proto_rawDescData)
	})
	return file_user_enum_proto_rawDescData
}

var file_user_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_enum_proto_goTypes = []interface{}{
	(UserEnum)(0), // 0: enum.UserEnum
}
var file_user_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_enum_proto_init() }
func file_user_enum_proto_init() {
	if File_user_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_enum_proto_goTypes,
		DependencyIndexes: file_user_enum_proto_depIdxs,
		EnumInfos:         file_user_enum_proto_enumTypes,
	}.Build()
	File_user_enum_proto = out.File
	file_user_enum_proto_rawDesc = nil
	file_user_enum_proto_goTypes = nil
	file_user_enum_proto_depIdxs = nil
}
