// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Req struct {
	FirstName string `path:"firstName"`
	LastName  string `form:"lastName"`
	Action    string `json:"action"`
}

type Res struct {
	Message string `json:"message"`
}
