// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: hello_enum.proto

package hello_enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEnum int32

const (
	ClientEnum_ClientEnumUnknown ClientEnum = 0
)

// Enum value maps for ClientEnum.
var (
	ClientEnum_name = map[int32]string{
		0: "ClientEnumUnknown",
	}
	ClientEnum_value = map[string]int32{
		"ClientEnumUnknown": 0,
	}
)

func (x ClientEnum) Enum() *ClientEnum {
	p := new(ClientEnum)
	*p = x
	return p
}

func (x ClientEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_hello_enum_proto_enumTypes[0].Descriptor()
}

func (ClientEnum) Type() protoreflect.EnumType {
	return &file_hello_enum_proto_enumTypes[0]
}

func (x ClientEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientEnum.Descriptor instead.
func (ClientEnum) EnumDescriptor() ([]byte, []int) {
	return file_hello_enum_proto_rawDescGZIP(), []int{0}
}

var File_hello_enum_proto protoreflect.FileDescriptor

var file_hello_enum_proto_rawDesc = []byte{
	0x0a, 0x10, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x2a, 0x23, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x45, 0x6e, 0x75, 0x6d, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hello_enum_proto_rawDescOnce sync.Once
	file_hello_enum_proto_rawDescData = file_hello_enum_proto_rawDesc
)

func file_hello_enum_proto_rawDescGZIP() []byte {
	file_hello_enum_proto_rawDescOnce.Do(func() {
		file_hello_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_hello_enum_proto_rawDescData)
	})
	return file_hello_enum_proto_rawDescData
}

var file_hello_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hello_enum_proto_goTypes = []interface{}{
	(ClientEnum)(0), // 0: enum.ClientEnum
}
var file_hello_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_enum_proto_init() }
func file_hello_enum_proto_init() {
	if File_hello_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hello_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hello_enum_proto_goTypes,
		DependencyIndexes: file_hello_enum_proto_depIdxs,
		EnumInfos:         file_hello_enum_proto_enumTypes,
	}.Build()
	File_hello_enum_proto = out.File
	file_hello_enum_proto_rawDesc = nil
	file_hello_enum_proto_goTypes = nil
	file_hello_enum_proto_depIdxs = nil
}
