// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hello.proto

package server

import (
	"context"

	"Quantum/interface/hello/pb/hello"
	"Quantum/service/hello/internal/logic"
	"Quantum/service/hello/internal/svc"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
	hello.UnimplementedHelloServer
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServer) Hello(ctx context.Context, in *hello.Request) (*hello.Response, error) {
	l := logic.NewHelloLogic(ctx, s.svcCtx)
	return l.Hello(in)
}
