name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

  workflow_dispatch:

env:
  ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
  ALIYUN_NAMESPACE: my-quantum

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}

      - name: set image tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "IMG_TAG=${{ github.event.workflow_run.head_sha }}" >> "$GITHUB_ENV"
          else
            echo "IMG_TAG=${{ github.sha }}" >> "$GITHUB_ENV"
          fi

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: upload deploy files
        run: |
          rsync -av --delete \
            build/podman/ \
            "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/quantum-podman/"

      - name: deploy
        run: |
          ssh "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "
            cd /tmp/quantum-podman &&

            ALIYUN_REGISTRY='${{ env.ALIYUN_REGISTRY }}' \
            ALIYUN_NAMESPACE='${{ env.ALIYUN_NAMESPACE }}' \
            ALIYUN_USERNAME='${{ secrets.ALIYUN_USERNAME }}' \
            ALIYUN_PASSWORD='${{ secrets.ALIYUN_PASSWORD }}' \
            IMG_TAG='${IMG_TAG}' \
            ./deploy.sh
          "